/**
 * Hand-written ESM shim re-exporting the named symbols of the autogenerated
 * CJS loader (`./index.js`) — same rationale as `@brainstorm-os/native`'s
 * `native.mjs` (the autogen's `module.exports = nativeBinding` defeats
 * Rollup's static named-export tracking; Vitest resolves the `import`
 * condition here). NOT regenerated by `napi build` — add a re-export whenever
 * a new `#[napi]` fn ships in `src/lib.rs`.
 */
import { createRequire } from "node:module";
import { applyPackagedNativeEnv } from "./packaged-resolver.cjs";

// Scope the global `NAPI_RS_NATIVE_LIBRARY_PATH` escape hatch to our own
// synchronous load (see loader.cjs).
const NATIVE_LIB_ENV = "NAPI_RS_NATIVE_LIBRARY_PATH";
const hadNativeLibEnv = NATIVE_LIB_ENV in process.env;
const prevNativeLibEnv = process.env[NATIVE_LIB_ENV];

applyPackagedNativeEnv();

const require = createRequire(import.meta.url);
let nativeBinding;
try {
	nativeBinding = require("./index.js");
} finally {
	if (hadNativeLibEnv) process.env[NATIVE_LIB_ENV] = prevNativeLibEnv;
	else delete process.env[NATIVE_LIB_ENV];
}

export const imageThumbnail = nativeBinding.imageThumbnail;
