/**
 * Hand-written ESM wrapper re-exporting the named symbols of the autogenerated
 * CJS loader (`./index.js`), mirroring `@brainstorm/native`'s `native.mjs`.
 *
 * NAPI-RS regenerates `index.js` on every `napi build` with a
 * `module.exports = nativeBinding` line that prevents Rollup from statically
 * tracking named exports, so ESM consumers (`import { embedBatch } from
 * "@brainstorm/native-embed"`) need this shim. Vitest resolves here via the
 * package.json `exports.".".import`. This file is NOT regenerated — add a
 * re-export below whenever a new `#[napi]` function ships in `src/lib.rs`.
 *
 * `applyPackagedNativeEnv()` primes `NAPI_RS_NATIVE_LIBRARY_PATH` for packaged
 * Electron; no-op in dev. `createRequire` (not a static import) so the env var
 * is set before the synchronous require.
 */
import { createRequire } from "node:module";
import { applyPackagedNativeEnv } from "./packaged-resolver.cjs";

const NATIVE_LIB_ENV = "NAPI_RS_NATIVE_LIBRARY_PATH";
const hadNativeLibEnv = NATIVE_LIB_ENV in process.env;
const prevNativeLibEnv = process.env[NATIVE_LIB_ENV];

applyPackagedNativeEnv();

const require = createRequire(import.meta.url);
let nativeBinding;
try {
	nativeBinding = require("./index.js");
} finally {
	if (hadNativeLibEnv) process.env[NATIVE_LIB_ENV] = prevNativeLibEnv;
	else delete process.env[NATIVE_LIB_ENV];
}

export const embedderInit = nativeBinding.embedderInit;
export const embedderReady = nativeBinding.embedderReady;
export const embedDim = nativeBinding.embedDim;
export const embedBatch = nativeBinding.embedBatch;
