/**
 * Per-app brand colour — the single source of truth for the app-icon glyphs.
 *
 * Each first-party app icon is a transparent glyph in this hue (the static
 * `apps/<dir>/icon.svg`, generated by `scripts/build-app-icons.ts` from this
 * map), sitting on the runtime frosted tile. Consumed at build time only —
 * re-running the generator recolours every glyph from one edit.
 *
 * Tuned to read on the frosted tile (a saturated mid-tone reads on both a
 * light and a dark frost), so the hex IS the final glyph colour — the
 * generator no longer darkens it. Hues are spread around the wheel and
 * grouped by family (warm apps warm, cool apps cool) so the suite is both
 * distinct and cohesive.
 */

export const APP_ICON_NEON: Readonly<Record<string, string>> = {
	"io.brainstorm.calendar": "#DC2626",
	"io.brainstorm.notes": "#EA580C",
	"io.brainstorm.journal": "#D97706",
	"io.brainstorm.tasks": "#CA8A04",
	"io.brainstorm.automations": "#65A30D",
	"io.brainstorm.code-editor": "#16A34A",
	"io.brainstorm.contacts": "#059669",
	"io.brainstorm.database": "#0D9488",
	"io.brainstorm.preview": "#0891B2",
	"io.brainstorm.mailbox": "#0E7490",
	"io.brainstorm.chat": "#0EA5E9",
	"io.brainstorm.browser": "#0284C7",
	"io.brainstorm.files": "#2563EB",
	"io.brainstorm.form-designer": "#4F46E5",
	"io.brainstorm.graph": "#7C3AED",
	"io.brainstorm.theme-editor": "#9333EA",
	"io.brainstorm.agent": "#C026D3",
	"io.brainstorm.books": "#DB2777",
	"io.brainstorm.bookmarks": "#E11D48",
	"io.brainstorm.whiteboard": "#64748B",
};
