/**
 * Hand-written ESM wrapper that re-exports the named symbols of the
 * autogenerated CJS loader (`./index.js`).
 *
 * NAPI-RS regenerates `index.js` on every `napi build` (which fires via the
 * `predev` / `pretest` / `build:native` hooks). The autogen emits a
 * `module.exports = nativeBinding` line BEFORE the per-symbol assignments,
 * which prevents Rollup from statically tracking the named exports.
 * Consumers writing `import { ed25519GetPublicKey } from "@brainstorm-os/native"`
 * then fail with `"ed25519GetPublicKey" is not exported by "../native/index.js"`
 * at bundle time.
 *
 * **Who actually consumes this shim today:**
 * - **Vitest** (the workspace test runner) — resolves `@brainstorm-os/native`
 *   via package.json `exports.".".import` → `native.mjs`. Without the shim,
 *   `bun --bun vitest` fails to import named symbols.
 * - **Future renderer / SDK consumers** — none today (all native imports
 *   live in `packages/shell/src/main/`), but ESM consumers in any future
 *   workspace package land here automatically.
 *
 * **Who does NOT use this shim** (despite the file's earlier docstring
 * claiming otherwise): the shell's main-process bundle. `electron-vite`'s
 * `externalizeDepsPlugin` externalizes `@brainstorm-os/native` (it's not in
 * the bundle exclude list), so production main code does
 * `require("@brainstorm-os/native")` at runtime, which resolves via
 * package.json's `exports.".".require` → `loader.cjs` (the packaged-mode
 * wrapper around the auto-generated `index.js`). The CJS named-export
 * assignments work fine under Node's CJS interop. Rollup never sees this
 * code path.
 *
 * 13.1b note: `applyPackagedNativeEnv()` primes `NAPI_RS_NATIVE_LIBRARY_PATH`
 * so the auto-generated loader picks up `process.resourcesPath/native/...`
 * in packaged Electron mode. No-op in dev. We use `createRequire` (not a
 * static `import`) because ESM imports run before any module code — we have
 * to set the env var first, then synchronously require the loader.
 *
 * This file is NOT regenerated — it stays exactly as written. Add a
 * re-export below whenever a new `#[napi]` function ships in `src/lib.rs`,
 * or ESM consumers will silently see `undefined` for the new symbol.
 */
import { createRequire } from "node:module";
import { applyPackagedNativeEnv } from "./packaged-resolver.cjs";

// `NAPI_RS_NATIVE_LIBRARY_PATH` is a GLOBAL escape hatch read by EVERY
// napi-rs-generated loader's first resolution branch, not just ours. Leaving
// it set makes sibling napi-rs addons (`@napi-rs/keyring`, `@napi-rs/canvas`)
// try to load *brainstorm-native's* binary as their own and fail ("Failed to
// load native binding"; for the keystore this surfaces as "No OS keystore is
// available"). Scope it to our own synchronous `require("./index.js")` (which
// runs the loader's `requireNative()` at module top-level) and restore it.
const NATIVE_LIB_ENV = "NAPI_RS_NATIVE_LIBRARY_PATH";
const hadNativeLibEnv = NATIVE_LIB_ENV in process.env;
const prevNativeLibEnv = process.env[NATIVE_LIB_ENV];

applyPackagedNativeEnv();

const require = createRequire(import.meta.url);
let nativeBinding;
try {
	nativeBinding = require("./index.js");
} finally {
	if (hadNativeLibEnv) process.env[NATIVE_LIB_ENV] = prevNativeLibEnv;
	else delete process.env[NATIVE_LIB_ENV];
}

export const argon2idDerive = nativeBinding.argon2idDerive;
export const ed25519GetPublicKey = nativeBinding.ed25519GetPublicKey;
export const ed25519Sign = nativeBinding.ed25519Sign;
export const ed25519Verify = nativeBinding.ed25519Verify;
export const hkdfSha256 = nativeBinding.hkdfSha256;
export const hpkeOpenBase = nativeBinding.hpkeOpenBase;
export const hpkeSealBase = nativeBinding.hpkeSealBase;
export const sha256 = nativeBinding.sha256;
export const smokeSum = nativeBinding.smokeSum;
export const x25519GetPublicKey = nativeBinding.x25519GetPublicKey;
export const x25519GetSharedSecret = nativeBinding.x25519GetSharedSecret;
export const xchacha20Poly1305Open = nativeBinding.xchacha20Poly1305Open;
export const xchacha20Poly1305Seal = nativeBinding.xchacha20Poly1305Seal;
